/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gudang.GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author Shoffan Darul Mufti
 */
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuForms = new javax.swing.JMenu();
        MenuTipeBarang = new javax.swing.JMenuItem();
        MenuKaryawan = new javax.swing.JMenuItem();
        MenuBarang = new javax.swing.JMenuItem();
        MenuBarangMasuk = new javax.swing.JMenuItem();
        MenuBarangKeluar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        MenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI GUDANG");

        jLabel2.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel2.setText("PROYEK AKHIR PEMROGRAMAN BERORIENTASI OBJEK (PBO)");

        jLabel3.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel3.setText("KELOMPOK 2");

        jLabel4.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel4.setText("ROBBY AKBAR ABDULLAH");

        jLabel5.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel5.setText("WILLIAM NISON MANURUNG");

        jLabel6.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel6.setText("SHOFFAN DARUL MUFTI");

        jLabel7.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel7.setText("FAJAR FIRDAUS DE ROOCK");

        jLabel8.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel8.setText("MUHAMMAD DAFFA RASYID");

        jLabel9.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel9.setText("2107421020");

        jLabel10.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel10.setText("2107421014");

        jLabel11.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel11.setText("2107421009");

        jLabel12.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel12.setText("2107421008");

        jLabel13.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        jLabel13.setText("2107421004");

        jButton1.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Product Sans", 1, 18)); // NOI18N
        jButton2.setText("MASUK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        MenuForms.setText("Forms");

        MenuTipeBarang.setText("Tipe Barang");
        MenuTipeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTipeBarangActionPerformed(evt);
            }
        });
        MenuForms.add(MenuTipeBarang);

        MenuKaryawan.setText("Karyawan");
        MenuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKaryawanActionPerformed(evt);
            }
        });
        MenuForms.add(MenuKaryawan);

        MenuBarang.setText("Barang");
        MenuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangActionPerformed(evt);
            }
        });
        MenuForms.add(MenuBarang);

        MenuBarangMasuk.setText("Barang Masuk");
        MenuBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangMasukActionPerformed(evt);
            }
        });
        MenuForms.add(MenuBarangMasuk);

        MenuBarangKeluar.setText("Barang Keluar");
        MenuBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarangKeluarActionPerformed(evt);
            }
        });
        MenuForms.add(MenuBarangKeluar);

        jMenu1.add(MenuForms);
        jMenu1.add(jSeparator2);

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        MenuAbout.setText("About this project");
        MenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAboutActionPerformed(evt);
            }
        });
        jMenu2.add(MenuAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))))
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuTipeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTipeBarangActionPerformed
        //        try {
            //            new TipeBarang().setVisible(true);
            //            this.setVisible(false);
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            //            System.out.println(e);
            //            e.printStackTrace();
            //        }
    }//GEN-LAST:event_MenuTipeBarangActionPerformed

    private void MenuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKaryawanActionPerformed
        //        try {
            //            new Karyawan().setVisible(true);
            //            this.setVisible(false);
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            //            System.out.println(e);
            //            e.printStackTrace();
            //        }
    }//GEN-LAST:event_MenuKaryawanActionPerformed

    private void MenuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangActionPerformed
        //        try {
            //            new Barang().setVisible(true);
            //            this.setVisible(false);
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            //            System.out.println(e);
            //            e.printStackTrace();
            //        }
    }//GEN-LAST:event_MenuBarangActionPerformed

    private void MenuBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangMasukActionPerformed
        //        try {
            //            new BarangMasuk().setVisible(true);
            //            this.setVisible(false);
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            //            System.out.println(e);
            //            e.printStackTrace();
            //        }
    }//GEN-LAST:event_MenuBarangMasukActionPerformed

    private void MenuBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarangKeluarActionPerformed
        //        try {
            //            new BarangKeluar().setVisible(true);
            //            this.setVisible(false);
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            //            System.out.println(e);
            //            e.printStackTrace();
            //        }
    }//GEN-LAST:event_MenuBarangKeluarActionPerformed

    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        try {
            System.exit(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        try {
            new About().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_MenuAboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            System.exit(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            new BarangMasuk().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Infobox: Error", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAbout;
    private javax.swing.JMenuItem MenuBarang;
    private javax.swing.JMenuItem MenuBarangKeluar;
    private javax.swing.JMenuItem MenuBarangMasuk;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenu MenuForms;
    private javax.swing.JMenuItem MenuKaryawan;
    private javax.swing.JMenuItem MenuTipeBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
